"""initial schema console 12 tables

Revision ID: 682a89c2f7d1
Revises: 
Create Date: 2026-06-22 15:26:49.266021

"""
from alembic import op
import sqlalchemy as sa


revision = '682a89c2f7d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('agent_key_hash', sa.String(length=64), nullable=True),
    sa.Column('remote_addr', sa.String(length=255), nullable=True),
    sa.Column('key_issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_pong_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_disconnect_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_agent_id'), 'agents', ['agent_id'], unique=True)
    op.create_table('command_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_command_events_event_type'), 'command_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_command_events_request_id'), 'command_events', ['request_id'], unique=False)
    op.create_table('commands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=255), nullable=False),
    sa.Column('agent_id', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=True),
    sa.Column('target_dir', sa.String(length=2048), nullable=False),
    sa.Column('target_image', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('original_request_id', sa.String(length=255), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.String(length=255), nullable=True),
    sa.Column('request_source', sa.String(length=255), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ack_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commands_agent_id'), 'commands', ['agent_id'], unique=False)
    op.create_index(op.f('ix_commands_original_request_id'), 'commands', ['original_request_id'], unique=False)
    op.create_index(op.f('ix_commands_request_id'), 'commands', ['request_id'], unique=True)
    op.create_index(op.f('ix_commands_status'), 'commands', ['status'], unique=False)
    op.create_table('fetch_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('namespace_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('plugin_id', sa.Integer(), nullable=False),
    sa.Column('plugin_version_id', sa.Integer(), nullable=False),
    sa.Column('fetch_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fetch_record_namespace_id'), 'fetch_record', ['namespace_id'], unique=False)
    op.create_index(op.f('ix_fetch_record_plugin_id'), 'fetch_record', ['plugin_id'], unique=False)
    op.create_index(op.f('ix_fetch_record_plugin_version_id'), 'fetch_record', ['plugin_version_id'], unique=False)
    op.create_index(op.f('ix_fetch_record_service_id'), 'fetch_record', ['service_id'], unique=False)
    op.create_table('namespace',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('pull_token_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_namespace_code'), 'namespace', ['code'], unique=True)
    op.create_table('plugin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plugin_code'), 'plugin', ['code'], unique=True)
    op.create_table('plugin_attachment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plugin_version_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plugin_version_id', name='uq_pa_plugin_version')
    )
    op.create_table('plugin_version',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plugin_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plugin_id', 'version', name='uq_pv_plugin_version')
    )
    op.create_index(op.f('ix_plugin_version_plugin_id'), 'plugin_version', ['plugin_id'], unique=False)
    op.create_table('rolling_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=255), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('degraded', sa.Boolean(), nullable=False),
    sa.Column('active_key', sa.String(length=512), nullable=True),
    sa.Column('nodes_json', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('active_key')
    )
    op.create_index(op.f('ix_rolling_tasks_agent_id'), 'rolling_tasks', ['agent_id'], unique=False)
    op.create_index(op.f('ix_rolling_tasks_service_name'), 'rolling_tasks', ['service_name'], unique=False)
    op.create_index(op.f('ix_rolling_tasks_status'), 'rolling_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_rolling_tasks_task_id'), 'rolling_tasks', ['task_id'], unique=True)
    op.create_table('service',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('namespace_id', sa.Integer(), nullable=False),
    sa.Column('service_code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('dir', sa.String(length=2048), nullable=True),
    sa.Column('default_image', sa.String(length=2048), nullable=True),
    sa.Column('nacos_service_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('namespace_id', 'service_code', name='uq_service_ns_code')
    )
    op.create_index(op.f('ix_service_namespace_id'), 'service', ['namespace_id'], unique=False)
    op.create_table('service_plugin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('plugin_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_id', 'plugin_id', name='uq_sp_service_plugin')
    )
    op.create_index(op.f('ix_service_plugin_plugin_id'), 'service_plugin', ['plugin_id'], unique=False)
    op.create_index(op.f('ix_service_plugin_service_id'), 'service_plugin', ['service_id'], unique=False)
    op.create_table('service_plugin_version',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_plugin_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('plugin_id', sa.Integer(), nullable=False),
    sa.Column('plugin_version_id', sa.Integer(), nullable=False),
    sa.Column('version_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_rolled_back', sa.Boolean(), nullable=False),
    sa.Column('spv_active_key', sa.String(length=191), nullable=True),
    sa.Column('publish_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spv_active_key')
    )
    op.create_index(op.f('ix_service_plugin_version_plugin_id'), 'service_plugin_version', ['plugin_id'], unique=False)
    op.create_index(op.f('ix_service_plugin_version_plugin_version_id'), 'service_plugin_version', ['plugin_version_id'], unique=False)
    op.create_index(op.f('ix_service_plugin_version_service_id'), 'service_plugin_version', ['service_id'], unique=False)
    op.create_index(op.f('ix_service_plugin_version_service_plugin_id'), 'service_plugin_version', ['service_plugin_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_plugin_version_service_plugin_id'), table_name='service_plugin_version')
    op.drop_index(op.f('ix_service_plugin_version_service_id'), table_name='service_plugin_version')
    op.drop_index(op.f('ix_service_plugin_version_plugin_version_id'), table_name='service_plugin_version')
    op.drop_index(op.f('ix_service_plugin_version_plugin_id'), table_name='service_plugin_version')
    op.drop_table('service_plugin_version')
    op.drop_index(op.f('ix_service_plugin_service_id'), table_name='service_plugin')
    op.drop_index(op.f('ix_service_plugin_plugin_id'), table_name='service_plugin')
    op.drop_table('service_plugin')
    op.drop_index(op.f('ix_service_namespace_id'), table_name='service')
    op.drop_table('service')
    op.drop_index(op.f('ix_rolling_tasks_task_id'), table_name='rolling_tasks')
    op.drop_index(op.f('ix_rolling_tasks_status'), table_name='rolling_tasks')
    op.drop_index(op.f('ix_rolling_tasks_service_name'), table_name='rolling_tasks')
    op.drop_index(op.f('ix_rolling_tasks_agent_id'), table_name='rolling_tasks')
    op.drop_table('rolling_tasks')
    op.drop_index(op.f('ix_plugin_version_plugin_id'), table_name='plugin_version')
    op.drop_table('plugin_version')
    op.drop_table('plugin_attachment')
    op.drop_index(op.f('ix_plugin_code'), table_name='plugin')
    op.drop_table('plugin')
    op.drop_index(op.f('ix_namespace_code'), table_name='namespace')
    op.drop_table('namespace')
    op.drop_index(op.f('ix_fetch_record_service_id'), table_name='fetch_record')
    op.drop_index(op.f('ix_fetch_record_plugin_version_id'), table_name='fetch_record')
    op.drop_index(op.f('ix_fetch_record_plugin_id'), table_name='fetch_record')
    op.drop_index(op.f('ix_fetch_record_namespace_id'), table_name='fetch_record')
    op.drop_table('fetch_record')
    op.drop_index(op.f('ix_commands_status'), table_name='commands')
    op.drop_index(op.f('ix_commands_request_id'), table_name='commands')
    op.drop_index(op.f('ix_commands_original_request_id'), table_name='commands')
    op.drop_index(op.f('ix_commands_agent_id'), table_name='commands')
    op.drop_table('commands')
    op.drop_index(op.f('ix_command_events_request_id'), table_name='command_events')
    op.drop_index(op.f('ix_command_events_event_type'), table_name='command_events')
    op.drop_table('command_events')
    op.drop_index(op.f('ix_agents_agent_id'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
